# 비트코인의 주 단위 캔들 정보를 최대한 과거 데이터 까지 가져온 후 시간순으로 정렬하기

In [6]:
import time
import requests
import pandas as pd
import json

In [7]:
datetimes = []
for year in range(2018,2025):
    datetimes.append(f"{year}-01-01T00%3A00%3A00%2B09%3A00")
datetimes

['2018-01-01T00%3A00%3A00%2B09%3A00',
 '2019-01-01T00%3A00%3A00%2B09%3A00',
 '2020-01-01T00%3A00%3A00%2B09%3A00',
 '2021-01-01T00%3A00%3A00%2B09%3A00',
 '2022-01-01T00%3A00%3A00%2B09%3A00',
 '2023-01-01T00%3A00%3A00%2B09%3A00',
 '2024-01-01T00%3A00%3A00%2B09%3A00']

In [8]:
headers = {"accept": "application/json"}
dfs = []
for datetime in datetimes:
    url = f"https://api.upbit.com/v1/candles/weeks?market=KRW-BTC&to={datetime}&count=53"
    response = requests.get(url, headers=headers)
    time.sleep(0.08)
    dfs.append(pd.DataFrame(json.loads(response.text)))

In [9]:
df = pd.concat(dfs)

In [10]:
df = df.drop(columns=["candle_date_time_utc", "timestamp", "first_day_of_period"])
df.columns = [
    "market",
    "datetime",
    "open",
    "high",
    "low",
    "close",
    "trade_price",
    "trade_volume",
]

In [11]:
df = df.sort_values(by="datetime").reset_index(drop=True)
df = df.drop_duplicates()
df

,market,datetime,open,high,low,close,trade_price,trade_volume
0,KRW-BTC,2017-09-25T09:00:00,4201000.0,4978000.0,4175000.0,4962000.0,1.677939e+09,374.805189
1,KRW-BTC,2017-10-02T09:00:00,4962000.0,5263000.0,4811000.0,5217000.0,1.163689e+09,231.455318
2,KRW-BTC,2017-10-09T09:00:00,5222000.0,6950000.0,5188000.0,6381000.0,4.960136e+08,82.704757
3,KRW-BTC,2017-10-16T09:00:00,6403000.0,7253000.0,5876000.0,7039000.0,6.822296e+08,106.952135
4,KRW-BTC,2017-10-23T09:00:00,7017000.0,7100000.0,6212000.0,6961000.0,1.436444e+10,2141.265727
...,...,...,...,...,...,...,...,...
327,KRW-BTC,2023-11-27T09:00:00,50210000.0,53864000.0,49500000.0,53700000.0,1.122036e+12,21904.936937
328,KRW-BTC,2023-12-04T09:00:00,53761000.0,61312000.0,53690000.0,59835000.0,2.925854e+12,49907.250404
329,KRW-BTC,2023-12-11T09:00:00,59834000.0,59924000.0,55460000.0,56710000.0,2.293218e+12,39598.394123
330,KRW-BTC,2023-12-18T09:00:00,56710000.0,60419000.0,55002000.0,58002000.0,2.082050e+12,35699.226661
331,KRW-BTC,2023-12-25T09:00:00,58002000.0,58659000.0,56000000.0,57047000.0,1.500536e+12,26230.477415